[project]
name = "tech-challenge-fase2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "db-dtypes>=1.7.1",
    "google-cloud-bigquery>=3.42.2",
    "google-cloud-storage>=3.13.0",
    "pandas>=3.0.5",
    "pyspark>=3.5.1",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.2",
]
